apiVersion: v1
kind: ConfigMap

metadata:
  name: postgres-init
  namespace: estoque-app

data:
  init.sql: |
    CREATE TABLE IF NOT EXISTS produtos (
        id SERIAL PRIMARY KEY,
        nome VARCHAR(100) NOT NULL,
        quantidade INTEGER NOT NULL,
        preco NUMERIC(10,2) NOT NULL,
        criado_em TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    );